### PR TITLE
Testnet validation bug fix (sync stop at block #4032)

### PR DESCRIPTION
**Pull request by thecodefactory**
This patch is so simple I'm not sure what could be breaking the travis builds.  I made it even simpler to try again.  If this fails to build on some platforms again, I will need a better understanding of what the build system is doing that can cause this breakage.  If it applies cleanly, please test :-)

This should be linked to https://github.com/libbitcoin/libbitcoin-server/issues/51 because it's the fix for it (not sure how to link issues either at this point).

### CODE REVIEW

**Comment by thecodefactory** [comment]
@evoskuil Your previous comment finally clicked and I do see that this failed due to 'Killed'.  Not sure what to do at the moment to do the individual test.  Any suggestions?

**Comment by evoskuil** [comment]
Just ignore the killed test problem, assuming the tests pass locally.

**Comment by thecodefactory** [comment]
Ok, merged and ready for testing.

**Comment by veox** [comment]
@thecodefactory It's past the halting block now (updated and started with same blockchain database, using default `consensus`).

**Comment by thecodefactory** [comment]
Great news, I am able to sync testnet easily within a day now, often in a couple of hours or less.  Let me know if any other snags or if it completes!

**Pull request merged**
